<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create Estimate</name>
   <tag></tag>
   <elementGuidId>33cdc5a9-9308-49a8-b1af-1009ad6acd49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div[2]/div/div/div[2]/div/div[2]/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Create Estimate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b784bb0-1b57-426e-b255-a1d7ecf249af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-normal</value>
      <webElementGuid>745bc9c6-38c3-47b3-8452-0eb224310dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Estimate</value>
      <webElementGuid>09194cb8-f8fe-497a-9d6a-1863113cfdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lg:hidden md:block block&quot;]/div[@class=&quot;flex relative&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;mx-auto max-w-full&quot;]/div[@class=&quot;p-4 space-y-4&quot;]/div[2]/div[@class=&quot;flex justify-between items-center space-x-5&quot;]/div[2]/div[@class=&quot;flex flex-row space-x-1&quot;]/button[@class=&quot;bg-primary-500 items-center text-white rounded-md lg:px-2 md:px-2 px-4 lg:text-sm md:text-sm text-xs hover:bg-primary-600 py-1.5 flex space-x-2&quot;]/div[@class=&quot;font-normal&quot;]</value>
      <webElementGuid>87f034e9-0fc2-4bc3-9041-976029ea7816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div[2]/div/div/div[2]/div/div[2]/div/button/div</value>
      <webElementGuid>564fefea-54b2-4b59-af52-f2e84adbba59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimates and Quotes'])[2]/following::div[5]</value>
      <webElementGuid>c46eb8d7-58a3-4821-8825-771dfce62c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revenue and Collections'])[5]/following::div[11]</value>
      <webElementGuid>3e3f1bb9-eef4-4800-b2bd-bc225a5be08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[2]/preceding::div[2]</value>
      <webElementGuid>8f3c5fb1-07ee-4747-a852-876a4da87167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[2]/preceding::div[2]</value>
      <webElementGuid>61df3ada-7e2b-4326-b3e5-dd7f21749b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div[2]/div/div[2]/div/button/div</value>
      <webElementGuid>f5203176-8f77-414f-b3bd-c143a6d27c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create Estimate' or . = 'Create Estimate')]</value>
      <webElementGuid>ade66fb2-b836-4153-8b6b-e41f2c259499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
