<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RyanBushZIRKELS SOLUTIONS INCBushSte_8aecc6</name>
   <tag></tag>
   <elementGuidId>c44f1fa9-0db9-40ce-b28a-ca96ce4fbb9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='customerID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;customerID&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;customerID&quot;] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2901ddfe-91f8-47f0-b18e-80111cc46214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerID</value>
      <webElementGuid>1eb1c114-a14d-4db5-8c50-3a89cf1b98db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full py-2 pl-3 pr-10 lg:text-sm md:text-sm focus:outline-none text-xs border-primary-300 focus:border-primary-500 focus:ring-primary-500 bg-green-50</value>
      <webElementGuid>45007c42-50f7-41f1-a079-ce213dd71094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RyanBushZIRKELS SOLUTIONS INCBushSteveDavid Bee</value>
      <webElementGuid>db953ace-8c1d-492c-91eb-cafb5e923772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lg:block md:hidden hidden lg:h-full lg:w-full&quot;]/div[@class=&quot;grid h-full gap-0 grid-cols-6&quot;]/div[@class=&quot;h-full col-span-5&quot;]/div[@class=&quot;mx-4&quot;]/div[@class=&quot;mx-auto max-w-full&quot;]/div[@class=&quot;p-4 space-y-4&quot;]/div[2]/div[@class=&quot;p-4 bg-white rounded-b-xl rounded-tr-xl&quot;]/div[@class=&quot;px-1&quot;]/div[@class=&quot;mx-auto w-full&quot;]/div[@class=&quot;overflow-visible bg-white sm:rounded-lg&quot;]/form[1]/div[@class=&quot;lg:px-6 md:px-4 px-2.5 space-y-6 pb-4&quot;]/div[@class=&quot;flex flex-col space-x-0 space-y-4 lg:flex-row lg:space-x-4 lg:space-y-0 lg:justify-between&quot;]/div[@class=&quot;lg:w-[73%] w-full md:w-full&quot;]/div[@class=&quot;flex flex-col w-full space-y-4&quot;]/div[1]/div[@class=&quot;flex rounded-md shadow-sm&quot;]/div[@class=&quot;relative flex flex-grow items-stretch focus-within:z-10&quot;]/select[@class=&quot;mt-1 block w-full py-2 pl-3 pr-10 lg:text-sm md:text-sm focus:outline-none text-xs border-primary-300 focus:border-primary-500 focus:ring-primary-500 bg-green-50&quot;]</value>
      <webElementGuid>08a50b8b-5235-4ca0-8478-c196762ae882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='customerID']</value>
      <webElementGuid>56da1ba8-43fb-4871-b254-6bc0b43d1a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/form/div/div/div/div/div/div/div/select</value>
      <webElementGuid>600d404c-7c70-42cc-a304-6e892a1cf03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::select[1]</value>
      <webElementGuid>7c9ae801-c243-408e-9603-2953a2e742c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recurring Invoice'])[3]/following::select[1]</value>
      <webElementGuid>e1a50d1f-2a66-4500-bfd4-b09467fd53ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Name'])[1]/preceding::select[1]</value>
      <webElementGuid>9dfc0ed4-985e-400c-8465-d65474e94f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::select[2]</value>
      <webElementGuid>87aca647-6962-4efc-bb46-e527e295070a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>69e9b98a-07ad-4dbd-82f3-e44a8a63c4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'customerID' and (text() = 'RyanBushZIRKELS SOLUTIONS INCBushSteveDavid Bee' or . = 'RyanBushZIRKELS SOLUTIONS INCBushSteveDavid Bee')]</value>
      <webElementGuid>a483da41-ae0d-4e3a-a1a9-bd1628b297cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
